/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.forms;

import business.controller.role.EditPersonRole.IEditPersonRole;
import business.controller.role.IRoleController;
import data.interfaces.DTOs.IDepartmentDTO;
import data.interfaces.DTOs.IPersonDTO;
import data.interfaces.DTOs.IRoleDTO;
import data.interfaces.DTOs.IRoleRightsDTO;
import data.interfaces.DTOs.ISportDTO;
import java.rmi.RemoteException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import presentation.tableModels.RoleTableModel;

/**
 *
 * @author Kno
 */
public class EditRolesForPersons extends javax.swing.JFrame {

    IPersonDTO person;
    IRoleController roles;
    RoleTableModel model;
    IEditPersonRole personrole;

    /**
     * Creates new form EditRolesForPersons
     */
    public EditRolesForPersons(IPersonDTO person, IRoleController roles, IEditPersonRole personrole) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Rolleneditor");
        this.person = person;
        this.personrole = personrole;
        lbPersonName.setText(person.getFirstname() + " " + person.getLastname());
        lbSportart.setEnabled(false);
        lbAbteilung.setEnabled(false);
        this.roles = roles;

        try {
            for (IDepartmentDTO dept : personrole.loadDepartments()) {
                lbAbteilung.addItem(dept);
            }
            for (IRoleRightsDTO role : roles.loadRoleRights()) {
                lbRolle.addItem(role);
            }
            List<IRoleDTO> a = roles.loadRolesOfPerson(person);
            for (IRoleDTO b : a) {
            }
            lbRolle.removeItemAt(0);
            lbAbteilung.removeItemAt(0);
            model = new RoleTableModel(a);
            table.setModel(model);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hinzufuegen = new javax.swing.JButton();
        lbSportart = new javax.swing.JComboBox();
        lbRolle = new javax.swing.JComboBox();
        lbPersonName = new javax.swing.JLabel();
        lbAbteilung = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(26);
        jScrollPane2.setViewportView(table);

        hinzufuegen.setText("Hinzufügen");
        hinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinzufuegenActionPerformed(evt);
            }
        });

        lbSportart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pony hunter" }));
        lbSportart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSportartActionPerformed(evt);
            }
        });

        lbRolle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "we are" }));
        lbRolle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbRolleActionPerformed(evt);
            }
        });

        lbAbteilung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "the golden" }));
        lbAbteilung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbAbteilungActionPerformed(evt);
            }
        });

        jLabel1.setText("Rolle");

        jLabel2.setText("Abteilung");

        jLabel3.setText("Sportart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbPersonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 146, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hinzufuegen, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbSportart, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbAbteilung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbRolle, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRolle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAbteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSportart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(hinzufuegen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRolleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbRolleActionPerformed
        String currentRolename = lbRolle.getSelectedItem().toString();
        IRoleRightsDTO dto = (IRoleRightsDTO) lbRolle.getSelectedItem();
        if (currentRolename.equals("Trainer") || currentRolename.equals("Sportler") || currentRolename.equals("Manager")) {
            lbAbteilung.setEnabled(true);
            lbSportart.setEnabled(false);
        } else {
            lbSportart.setEnabled(false);
            lbAbteilung.setEnabled(false);
        }
    }//GEN-LAST:event_lbRolleActionPerformed

    private void hinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinzufuegenActionPerformed
        try {
            LinkedList<IRoleRightsDTO> list = new LinkedList<IRoleRightsDTO>();

            list.add((IRoleRightsDTO) lbRolle.getSelectedItem());


            if (!lbAbteilung.isEnabled()) //nur rolle gewählt
            {
                roles.EditPersonRole(person, list, null, null);
            } else if (!lbSportart.isEnabled()) //rolle + abteilung
            {
                roles.EditPersonRole(person, list, (IDepartmentDTO) lbAbteilung.getSelectedItem(), null);
            } else //alles
            {
                roles.EditPersonRole(person, list, (IDepartmentDTO) lbAbteilung.getSelectedItem(), (ISportDTO) lbSportart.getSelectedItem());
            }
            List<IRoleDTO> a = roles.loadRolesOfPerson(person);
            model = new RoleTableModel(a);
            table.setModel(model);
        } catch (RemoteException ex) {
            Logger.getLogger(EditRolesForPersons.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hinzufuegenActionPerformed

    private void lbSportartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSportartActionPerformed
        //TODO
    }//GEN-LAST:event_lbSportartActionPerformed

    private void lbAbteilungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbAbteilungActionPerformed
        String currentRolename = lbRolle.getSelectedItem().toString();
        IDepartmentDTO dept = (IDepartmentDTO) lbAbteilung.getSelectedItem();
        lbSportart.setEnabled(true);
        lbSportart.setModel(new javax.swing.DefaultComboBoxModel());
        for (ISportDTO sport : dept.getSports()) {
            lbSportart.addItem(sport);
        }
        if (currentRolename.equals("Manager")) {
            lbSportart.setEnabled(false);
        }
    }//GEN-LAST:event_lbAbteilungActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hinzufuegen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox lbAbteilung;
    private javax.swing.JLabel lbPersonName;
    private javax.swing.JComboBox lbRolle;
    private javax.swing.JComboBox lbSportart;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
